server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chinthaka103/spring-cloud-config-store
          search-paths:
          - 'primary-config-store/*service'
